/* 
 * DocuSign Click API
 *
 * Elastic signing (also known as DocuSign Click)  lets you capture consent to standard agreement terms with a single click: terms and conditions, terms of service, terms of use, privacy policies, and more. The Click API lets you include this customizable elastic template solution in your DocuSign integrations.
 *
 * OpenAPI spec version: v1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = DocuSign.Click.Client.SwaggerDateConverter;

namespace DocuSign.Click.Model
{
    /// <summary>
    /// ClickwrapsDeleteResponse
    /// </summary>
    [DataContract]
    public partial class ClickwrapsDeleteResponse :  IEquatable<ClickwrapsDeleteResponse>, IValidatableObject
    {
        public ClickwrapsDeleteResponse()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickwrapsDeleteResponse" /> class.
        /// </summary>
        /// <param name="Clickwraps">An array of clickwrap deletion results..</param>
        public ClickwrapsDeleteResponse(List<ClickwrapDeleteResponse> Clickwraps = default(List<ClickwrapDeleteResponse>))
        {
            this.Clickwraps = Clickwraps;
        }
        
        /// <summary>
        /// An array of clickwrap deletion results.
        /// </summary>
        /// <value>An array of clickwrap deletion results.</value>
        [DataMember(Name="clickwraps", EmitDefaultValue=false)]
        public List<ClickwrapDeleteResponse> Clickwraps { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClickwrapsDeleteResponse {\n");
            sb.Append("  Clickwraps: ").Append(Clickwraps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ClickwrapsDeleteResponse);
        }

        /// <summary>
        /// Returns true if ClickwrapsDeleteResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ClickwrapsDeleteResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClickwrapsDeleteResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Clickwraps == other.Clickwraps ||
                    this.Clickwraps != null &&
                    this.Clickwraps.SequenceEqual(other.Clickwraps)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Clickwraps != null)
                    hash = hash * 59 + this.Clickwraps.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
