/* 
 * DocuSign Click REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = DocuSign.Click.Client.SwaggerDateConverter;

namespace DocuSign.Click.Model
{
    /// <summary>
    /// RecipientCopyRequest
    /// </summary>
    [DataContract]
    public partial class RecipientCopyRequest :  IEquatable<RecipientCopyRequest>, IValidatableObject
    {
        public RecipientCopyRequest()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecipientCopyRequest" /> class.
        /// </summary>
        /// <param name="ClientUserEmail">ClientUserEmail.</param>
        public RecipientCopyRequest(string ClientUserEmail = default(string))
        {
            this.ClientUserEmail = ClientUserEmail;
        }
        
        /// <summary>
        /// Gets or Sets ClientUserEmail
        /// </summary>
        [DataMember(Name="clientUserEmail", EmitDefaultValue=false)]
        public string ClientUserEmail { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RecipientCopyRequest {\n");
            sb.Append("  ClientUserEmail: ").Append(ClientUserEmail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as RecipientCopyRequest);
        }

        /// <summary>
        /// Returns true if RecipientCopyRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of RecipientCopyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecipientCopyRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ClientUserEmail == other.ClientUserEmail ||
                    this.ClientUserEmail != null &&
                    this.ClientUserEmail.Equals(other.ClientUserEmail)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ClientUserEmail != null)
                    hash = hash * 59 + this.ClientUserEmail.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
