/* 
 * DocuSign Click API
 *
 * Elastic signing (also known as DocuSign Click)  lets you capture consent to standard agreement terms with a single click: terms and conditions, terms of service, terms of use, privacy policies, and more. The Click API lets you include this customizable elastic template solution in your DocuSign integrations.
 *
 * OpenAPI spec version: v1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = DocuSign.Click.Client.SwaggerDateConverter;

namespace DocuSign.Click.Model
{
    /// <summary>
    /// ServiceInformation
    /// </summary>
    [DataContract]
    public partial class ServiceInformation :  IEquatable<ServiceInformation>, IValidatableObject
    {
        public ServiceInformation()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceInformation" /> class.
        /// </summary>
        /// <param name="BuildBranch">The internal source control branch..</param>
        /// <param name="BuildBranchDeployedDateTime">The date-time this branch was deployed..</param>
        /// <param name="BuildSHA">The internal source control SHA..</param>
        /// <param name="BuildVersion">The internal build version information..</param>
        /// <param name="LinkedSites">An array of URLs (strings) of related sites..</param>
        /// <param name="ServiceVersions">An array of &#x60;serviceVersion&#x60; objects..</param>
        public ServiceInformation(string BuildBranch = default(string), string BuildBranchDeployedDateTime = default(string), string BuildSHA = default(string), string BuildVersion = default(string), List<string> LinkedSites = default(List<string>), List<ServiceVersion> ServiceVersions = default(List<ServiceVersion>))
        {
            this.BuildBranch = BuildBranch;
            this.BuildBranchDeployedDateTime = BuildBranchDeployedDateTime;
            this.BuildSHA = BuildSHA;
            this.BuildVersion = BuildVersion;
            this.LinkedSites = LinkedSites;
            this.ServiceVersions = ServiceVersions;
        }
        
        /// <summary>
        /// The internal source control branch.
        /// </summary>
        /// <value>The internal source control branch.</value>
        [DataMember(Name="buildBranch", EmitDefaultValue=false)]
        public string BuildBranch { get; set; }
        /// <summary>
        /// The date-time this branch was deployed.
        /// </summary>
        /// <value>The date-time this branch was deployed.</value>
        [DataMember(Name="buildBranchDeployedDateTime", EmitDefaultValue=false)]
        public string BuildBranchDeployedDateTime { get; set; }
        /// <summary>
        /// The internal source control SHA.
        /// </summary>
        /// <value>The internal source control SHA.</value>
        [DataMember(Name="buildSHA", EmitDefaultValue=false)]
        public string BuildSHA { get; set; }
        /// <summary>
        /// The internal build version information.
        /// </summary>
        /// <value>The internal build version information.</value>
        [DataMember(Name="buildVersion", EmitDefaultValue=false)]
        public string BuildVersion { get; set; }
        /// <summary>
        /// An array of URLs (strings) of related sites.
        /// </summary>
        /// <value>An array of URLs (strings) of related sites.</value>
        [DataMember(Name="linkedSites", EmitDefaultValue=false)]
        public List<string> LinkedSites { get; set; }
        /// <summary>
        /// An array of &#x60;serviceVersion&#x60; objects.
        /// </summary>
        /// <value>An array of &#x60;serviceVersion&#x60; objects.</value>
        [DataMember(Name="serviceVersions", EmitDefaultValue=false)]
        public List<ServiceVersion> ServiceVersions { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceInformation {\n");
            sb.Append("  BuildBranch: ").Append(BuildBranch).Append("\n");
            sb.Append("  BuildBranchDeployedDateTime: ").Append(BuildBranchDeployedDateTime).Append("\n");
            sb.Append("  BuildSHA: ").Append(BuildSHA).Append("\n");
            sb.Append("  BuildVersion: ").Append(BuildVersion).Append("\n");
            sb.Append("  LinkedSites: ").Append(LinkedSites).Append("\n");
            sb.Append("  ServiceVersions: ").Append(ServiceVersions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ServiceInformation);
        }

        /// <summary>
        /// Returns true if ServiceInformation instances are equal
        /// </summary>
        /// <param name="other">Instance of ServiceInformation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceInformation other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.BuildBranch == other.BuildBranch ||
                    this.BuildBranch != null &&
                    this.BuildBranch.Equals(other.BuildBranch)
                ) && 
                (
                    this.BuildBranchDeployedDateTime == other.BuildBranchDeployedDateTime ||
                    this.BuildBranchDeployedDateTime != null &&
                    this.BuildBranchDeployedDateTime.Equals(other.BuildBranchDeployedDateTime)
                ) && 
                (
                    this.BuildSHA == other.BuildSHA ||
                    this.BuildSHA != null &&
                    this.BuildSHA.Equals(other.BuildSHA)
                ) && 
                (
                    this.BuildVersion == other.BuildVersion ||
                    this.BuildVersion != null &&
                    this.BuildVersion.Equals(other.BuildVersion)
                ) && 
                (
                    this.LinkedSites == other.LinkedSites ||
                    this.LinkedSites != null &&
                    this.LinkedSites.SequenceEqual(other.LinkedSites)
                ) && 
                (
                    this.ServiceVersions == other.ServiceVersions ||
                    this.ServiceVersions != null &&
                    this.ServiceVersions.SequenceEqual(other.ServiceVersions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.BuildBranch != null)
                    hash = hash * 59 + this.BuildBranch.GetHashCode();
                if (this.BuildBranchDeployedDateTime != null)
                    hash = hash * 59 + this.BuildBranchDeployedDateTime.GetHashCode();
                if (this.BuildSHA != null)
                    hash = hash * 59 + this.BuildSHA.GetHashCode();
                if (this.BuildVersion != null)
                    hash = hash * 59 + this.BuildVersion.GetHashCode();
                if (this.LinkedSites != null)
                    hash = hash * 59 + this.LinkedSites.GetHashCode();
                if (this.ServiceVersions != null)
                    hash = hash * 59 + this.ServiceVersions.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
